### PR TITLE
feat: support corePackage/jsxPackage options

### PR DESCRIPTION
**Pull request by mogelbrod**
I was trying to configure the [macro `corePackage`/`jsxPackage` settings](https://lingui.dev/ref/conf#macrocorepackage) available in the babel implementation, but noticed that they weren't supported by the SWC plugin. This PR should add support for them.

Disclaimer: My rust knowledge is very limited; most rust code was generated by GPT-5.4.

### CODE REVIEW

File: src/options.rs [hunk 1]
```diff
@@ -63,6 +67,40 @@ pub struct RuntimeModulesConfigMapNormalized {
...
+                .any(|existing| existing == package)
+            {
+                continue;
+            }
+
+            all_macro_packages.push(package.clone());
+        }
+
+        all_macro_packages
+    }
```
Comment (mogelbrod) [inline src/options.rs:92]: This defines a normalized vector acting like a set of both core/jsx imports to minimize the overhead.

Comment (timofei-iatsenko) [reply src/options.rs:92]: I think Rust has a Set datatype in the standart library, so you can use 

```rust
use std::collections::HashSet;

fn main() {
    // 1. Creation
    let mut books = HashSet::new();

    // 2. Insertion
    books.insert("The Hobbit");
    books.insert("Dune");
    books.insert("The Hobbit"); // This is a duplicate and will be ignored

    // 3. Check for existence
    if !books.contains("Neuromancer") {
        println!("We don't have Neuromancer yet.");
    }

    // 4. Removal
    books.remove("Dune");

    // 5. Iteration
    for book in &books {
        println!("{}", book);
    }
}
```

And it should be slightly faster that look up in vector

**Review by timofei-iatsenko — CHANGES_REQUESTED** [review]

File: src/options.rs (hunk 1 above)
Comment (mogelbrod) [reply src/options.rs:92]: When I implemented this I actually asked Copilot if switching to a set would be better and got the following response:

> So the current cost is a handful of string comparisons per import declaration. A HashSet would add its own allocation and hashing overhead, and for such a small fixed cardinality that usually loses or is at best noise. I would only switch to a HashSet if one of these becomes true:
> - package lists are expected to grow materially
> - this membership check starts happening in a hotter path than module-import scanning
> - profiling shows this comparison is measurable

If you want I'll refactor it to use a `HashSet`, but figured I'd provide some context first.

**Review by timofei-iatsenko — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
Guys, it looks like the CI started to fail after merging this PR. 

Here: https://github.com/lingui/swc-plugin/pull/222

```console
Run cargo clippy --all-targets --all-features -- -D warnings
    Updating crates.io index
    Checking lingui_macro_plugin v6.3.0 (/home/runner/work/swc-plugin/swc-plugin)
error[E0063]: missing fields `core_package` and `jsx_package` in initializer of `options::LinguiJsOptions`
Error:    --> src/options.rs:276:13
    |
276 |             LinguiJsOptions {
    |             ^^^^^^^^^^^^^^^ missing `core_package` and `jsx_package`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `lingui_macro_plugin` (lib test) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

**Comment by mogelbrod** [comment]
@andrii-bodnar that's weird - I saw no reports in this PR. Maybe the `main` branch runs more extensive checks?

@timofei-iatsenko do you want to fix this as part of the other changes or should I?
